name: check
 
on:
  issues:
    types: [opened]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Run Action
        uses: anushkrishnav/Issue-Watcher@dev
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          author: '${{github.actor}}'
          repo: Not-a-Bomb/Build
          maxIssue: 2
